### ISSUE TITLE
repo structure

### ISSUE THREAD

**Issue by rgommers** [mingwpy/mingwpy.github.io#13]
I propose to:
- delete `_sources/issues.txt` (unused, and the same as `issues.rst`)
- move the reST content into a `source/` dir. Mixing source .rst files with make/config/README files is going to get messy when the amount of files grows.

One that I care less about but may also make sense: use standard branch names, so `master` for content and `gh-pages` for generated html. 99.9% of git users expect the default branch to be `master`.

**Comment by rgommers** [comment]
I can do the work if you all agree.

**Comment by techtonik** [comment]
>  99.9% of git users expect the default branch to be master.

99.9% of git users don't care about this repository. =)

I mean - let's polish other things.. like add diagrams. Because the value of content depends on representation and these changes are a bit meta.

**Comment by techtonik** [comment]
But maybe it will help if I say that I find `gh-pages` very unintuitive hack.

**Comment by techtonik** [comment]
It is not a branch - it is generated content.

**Comment by matthew-brett** [comment]
Ralf - do you know how to get github to render the pages correctly if the pages are not in master?   I couldn't work it out at a first pass, but if you can, please go for it.

**Comment by matthew-brett** [comment]
Please do delete `_sources/issues.txt` - I'm not sure how that got in there.

I personally prefer not to have the extra `sources/` directory, but I don't feel strongly about it, please do go ahead if you do.

**Comment by rgommers** [comment]
I'll try to figure out the rendering thing - I'm sure that that used to work for other branches.

**Comment by rgommers** [comment]
Deleted `issues.txt` in gh-18.

**Comment by matthew-brett** [comment]
Oh - whoops, I just pushed the deletion, shouldn't have, won't do it again :)

**Comment by rgommers** [comment]
> Oh - whoops, I just pushed the deletion, shouldn't have, won't do it again :)

Weirdly, we now have the same commit twice and git didn't complain?? Well, whatever - it looks OK now.

**Comment by rgommers** [comment]
> I'll try to figure out the rendering thing - I'm sure that that used to work for other branches.

OK not going to work like this - for some reason there's a difference between org and project pages in this respect: https://help.github.com/articles/user-organization-and-project-pages/
So let's live with it.
