### ISSUE TITLE
content on website for which reST sources are missing

### ISSUE THREAD

**Issue by rgommers** [mingwpy/mingwpy.github.io#16]
These pages are visible on the website and have been checked into `master` as html, but the `reST` sources are missing completely:

http://mingwpy.github.io/windows-dll-notes.html
http://mingwpy.github.io/whats-with-windows-builds.html

Not sure if there are more pages like that.

**Comment by carlkl** [comment]
I guess Matthew has copied it from numpy wiki. Both pages has to be reworked nevertheless and integrated into the repository. I propose I start with integrating the necessary informations of the numpy wiki pages.

**Comment by rgommers** [comment]
Sure. Might make sense to start with new content though, because it looks like @matthew-brett has already done the Markdown to reST conversion in order to produce those pages (you don't want to do double work...).

**Comment by matthew-brett** [comment]
Sorry, I have those pages in my local copy, but not checked into source.

I haven't modified either of those pages from the wiki, in fact, I think the windows builds page is an older version than on the wiki.

So, I think I should just delete the html pages, otherwise it might confusing.  OK with y'all?

**Comment by rgommers** [comment]
sure

**Comment by matthew-brett** [comment]
OK - I just deleted the `_sources/issues.txt`, and pushed.

I rebuilt the pages too, so I think those extra pages should be gone now.

**Comment by rgommers** [comment]
they're gone now, thanks.
