### ISSUE TITLE
broken CBLAS link

### ISSUE THREAD

**Issue by pierre-haessig** [mingwpy/mingwpy.github.io#21]
the link to CBLAS http://www.prism.gatech.edu/~ndantam3/cblas-doc/doc/html/main.html on page http://mingwpy.github.io/blas_lapack.html is broken. In fact http://www.prism.gatech.edu/~ndantam3/ itself is broken (404 not found).

**Comment by matthew-brett** [comment]
Thanks for reporting ... fixed here - https://github.com/mingwpy/mingwpy.github.io/pull/22

**Comment by carlkl** [comment]
thanks for fixing
