### ISSUE TITLE
make Github web interface show the real activity on mingwpy/mingw-builds

### ISSUE THREAD

**Issue by stonebig** [mingwpy/mingwpy.github.io#36]
Would it be possible to modify github settings of mingwpy/mingw-builds so it shows the actual dev branch "develop" instead of the default "master" ? (when  you look at project via the github web interface)

**Comment by carlkl** [comment]
done for both mingw-builds and my OpenBLAS fork.

Carl

2016-02-23 9:10 GMT+01:00 stonebig notifications@github.com:

**Comment by stonebig** [comment]
Thanks, Carl
